version: 2

sphinx:
  configuration: docs/conf.py
  builder: html
#  fail_on_warning: true

formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements_docs.txt

#submodules:
#  include: all
