name: Check-Documentation

on:
  workflow_call:

jobs:
  build:
    name: Check Documentation ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.11']
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install rst checker
        run: pip install rstcheck

      - name: Check documents
        run: rstcheck README.rst

      - name: Install md formatter
        run: pip install mdformat

      - name: Check documents
        run: mdformat RELEASE.md
