name: CI

on:
  workflow_call:

jobs:
  CI:
    runs-on: ${{matrix.os}}
    env:
      MYSQL_DATABASE: ${{vars.MYSQL_DATABASE}}
      MYSQL_HOST:  ${{vars.MYSQL_HOST}}
      MYSQL_ROOT_PWD:  ${{vars.MYSQL_ROOT_PWD}}
      MYSQL_TCP_PORT: ${{vars.MYSQL_TCP_PORT}}
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        os: ['ubuntu-latest']
    services:
      mysql:
        image: mysql:8.0.21
        ports:
          - ${{vars.MYSQL_TCP_PORT}}:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
#          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ${{vars.MYSQL_ROOT_PWD}}
          MYSQL_DATABASE: ${{vars.MYSQL_DATABASE}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Verify DB exists
        run: mysql --host 127.0.0.1 -uroot -p${{vars.MYSQL_ROOT_PWD}} -e "SHOW DATABASES"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

#      - name: Install dependencies
#        run: pip install -r ./requirements/requirements.txt

      - name: Install editable package
        run: pip install -e .[dev]

      - name: Run pytest
        run: pytest --cov=./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
