name: CI

on:
  workflow_call:

jobs:
  CI:
    runs-on: ${{matrix.os}}
#    env:
#      MYSQL_DB_NAME: SQLAlchemyExample
#      MYSQL_DATABASE: SQLAlchemyExample
#      MYSQL_HOST: localhost
#      MYSQL_PASSWORD: N0tS0S3curePassw0rd
#      MYSQL_PWD: N0tS0S3curePassw0rd
#      MYSQL_ROOT_PWD: N0tS0S3curePassw0rd
#      MYSQL_TCP_PORT_EXAMPLES: 50002
#      MYSQL_TCP_PORT: 50002
#      SQLALCHEMY_SILENCE_UBER_WARNING: 1
    strategy:
      fail-fast: true
      matrix:
#        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
#        python-version: ['3.7', '3.8', '3.9', 3.10]
        os: ['ubuntu-latest']
        python-version: ['3.10']
    services:
      mysql:
        image: mysql:8.0.21
        ports:
          - ${{vars.MYSQL_TCP_PORT}}:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
#          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ${{vars.MYSQL_ROOT_PWD}}
          MYSQL_DATABASE: ${{vars.MYSQL_DB_NAME}}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Verify DB exists
        run: mysql --host 127.0.0.1 -uroot -p${{vars.MYSQL_ROOT_PWD}} -e "SHOW DATABASES" # LIKE 'SQLAlchemyExample'"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install editable package
        run: pip install -e .

      - name: Run pytest
        run: pytest --cov=./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
