name: CI


on:
  pull_request:
  push:
    branches:
      - master

env:
  MYSQL_DB_NAME: SQLAlchemyExample
  MYSQL_DATABASE: $MYSQL_DB_NAME
  MYSQL_HOST: localhost
  MYSQL_PASSWORD: N0tS0S3curePassw0rd
  MYSQL_PWD: $MYSQL_PASSWORD
  MYSQL_TCP_PORT_EXAMPLES: 50002
  MYSQL_TCP_PORT: 50002
  SQLALCHEMY_SILENCE_UBER_WARNING: 1

jobs:
  pytest:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
#        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        os: ['ubuntu-latest']
#        python-version: ['3.7', '3.8', '3.9', 3.10]
        python-version: ['3.10']
    services:
      mysql:
        image: mysql:8.0.21
        ports:
          - ${{MYSQL_TCP_PORT_EXAMPLES}}::3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
#          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Verify DB exists
#        run: mysql --host 127.0.0.1 --port 50002 -uroot -e "SHOW DATABASES LIKE 'SQLAlchemyExample'"
        run: mysql --host 127.0.0.1 -uroot -e "SHOW DATABASES LIKE 'SQLAlchemyExample'"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install editable package
        run: pip install -e .

      - name: Run pytest
        run: pytest --cov=./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
