name: Pre-Commit

on:
#  pull_request:
#  push:
  workflow_call:

jobs:
  Pre-Commit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
#        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        os: ['ubuntu-latest']
#        python-version: ['3.7', '3.8', '3.9', 3.10]
        python-version: ['3.10']
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
#
#      - name: Install pre-commit
#        run: pip install pre-commit
#
#      - name: Run pre-commit checks
#        uses: pre-commit/action@v3.0.0
