name: BEE Default Workflow

on:
  pull_request:
  push:

jobs:
  Pre-Commit:
    uses: .github/workflows/pre-commit.yaml
    secrets:
      token: ${{ secrets.token }}

#  CI:
#    uses: .github/workflows/ci.yaml
#    secrets:
#      token: ${{ secrets.token }}

  Release:
    uses: .github/workflows/release.yaml
    if: startsWith(github.ref, 'refs/tags/')
    secrets:
      token: ${{ secrets.token }}
