name: Pre-commit, pytest CI, and MySQL setup

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.0

  pytest:
    needs: pre-commit
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: N0tS0S3curePassw0rd
        ports:
          - 50002:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      MYSQL_DB_NAME: SQLAlchemyExample
      MYSQL_HOST: localhost
      MYSQL_ROOT_PWD: N0tS0S3curePassw0rd
      MYSQL_TCP_PORT_EXAMPLES: 50002
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --cov=./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
