name: BEE Default Workflow

on:
  pull_request:
  push:

jobs:
  Pre-Commit:
    uses: ./.github/workflows/pre-commit.yml
#    secrets:
#      token: ${{ secrets.token }}

  CI:
    uses: ./.github/workflows/ci.yml
    needs: Pre-Commit
#    secrets:
#      token: ${{ secrets.token }}

  Build-and-Release-to-Pypi:
    needs: CI
    uses: ./.github/workflows/build-and-release-to-pypi.yml
    if: startsWith(github.ref, 'refs/tags/')
#    if: github.repository == 'hendrikdutoit/PackageIt' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#    secrets:
#      token: ${{ secrets.token }}
